### ISSUE TITLE
Annotation for transposon insertion 

### ISSUE THREAD

**Issue by kevinchenyutang** [WGLab/doc-ANNOVAR#28]
Hi,

I have a vcf file from transposon detection software Mobster that looks like this:

CHROM   POS       ID    REF      ALT            QUAL   FILTER    
chr11     34288       .     .     <INS:ME:ALU>    .       PASS
chr11     43445       .     .     <INS:ME:L1>       .       PASS
chr11     67645       .     .     <INS:ME:SVA>    .       PASS

I want to annotate these transposon insertion points and I've used ANNOVAR hg19 refGene. However, all of these insertion points are being treated as invalid inputs. Is it because there is no ref and alt bases? Is it possible to annotate it with ANNOVAR?

Thanks,

**Comment by kaichop** [comment]
This format cannot be annotated by ANNOVAR (since the actual inserted
sequence is not specified). But if you are interested in annotating the
breakpoint itself, you can use 0 as the ref and alt allele, for example,
"chr11 34288 34288 0 0" will work as avinput format. If the inserted
sequence is not that long (say for example 300bp for Alu) and if it is in
an exon, you may actually just do a "chr11 34288 34288 - ACGTGACATGAT" and
can get the exact protein sequence out using coding_change.pl. That's
probably what you really need.
