### ISSUE TITLE
Error: Exonic variant "unknown" when set "--splicing_threshold 10"

### ISSUE THREAD

**Issue by haiwufan** [WGLab/doc-ANNOVAR#29]
Hi developer
I find some variants in exonic region with 'unknown'  when setting "--splicing_threshold 10".

Before：
[Normal.xlsx](https://github.com/WGLab/doc-ANNOVAR/files/1940635/Normal.xlsx)

I change table_annovar.pl script, add "--splicing_threshold 10" & “-hgvs”.

387c387
< 	$sc = "annotate_variation.pl -geneanno -buildver $buildver --splicing_threshold 10 -hgvs -dbtype $protocol -outfile $tempfile.$protocol -exonsort $queryfile $dbloc";
---
> 	$sc = "annotate_variation.pl -geneanno -buildver $buildver -dbtype $protocol -outfile $tempfile.$protocol -exonsort $queryfile $dbloc"; 

After:
[Error.xlsx](https://github.com/WGLab/doc-ANNOVAR/files/1940705/Error.xlsx)

How can I resolve this problem?

Thanks!
Wufan Hai

**Comment by kaichop** [comment]
"unknown" happens when there is no confidence to generate c. notation (for
example, due to lack of complete ORF when an annotated transcript has a
stop codon inside the protein sequence in refGene). You may try to use a
different gene definition (such as GENCODE) and see if this gene definition
can generate c. notation for these genes.

Also, by the way, you can use -arg argument to supply argument to
table_annovar.pl for each annotation. There is no need to actually change
the source code.
