### ISSUE TITLE
convert vcf4 to avinput

### ISSUE THREAD

**Issue by zhengxinchang** [WGLab/doc-ANNOVAR#58]
Hi, developers
I am confused when I convert vcf(vcf4) to avinput format.
for instance,
In the output file I see conversion like this:
origin record:
chr1    9671257 .       CTTTT   C,CT,CTT,CTTT,CTTTTT
convertion:
chr1	9671259	9671261	TTT	-
chr1	9671260	9671261	TT	-
chr1	9671261	9671261	T	-
chr1	9671261	9671261	-	T
**the end positions are same.**

but in some records like this:
origin record:
chr1    36203712        .       AAAATATATATAT   A,AAT,AATAT,AATATAT
conversion:
chr1	36203713	36203724	AAATATATATAT	-
chr1	36203713	36203722	AAATATATAT	-
chr1	36203713	36203720	AAATATAT	-
chr1	36203713	36203718	AAATAT	-
**However，the start positions are same in this conversion.**

Dr wang have mentioned ANNOVAR will left-align both input vcf  and database in the documation.  I also compare the results from gatk4 LeftAlignAndTrimVariants tool. the conversions about the two records like this:

chr1	9671257	.	CTTTT	C
chr1	9671257	.	CTTT	C
chr1	9671257	.	CTT	C
chr1	9671257	.	CT	C
chr1	9671257	.	C	CT

chr1	36203712	.	AAAATATATATAT	A
chr1	36203712	.	AAAATATATAT	A
chr1	36203712	.	AAAATATAT	A
chr1	36203712	.	AAAATAT	A

Despite  the way to show ref and alt bases,  I saw that both conversions have same POS.

I wonder know does these conversion make sense? and could you please give me a brief description about the algrithm that be used in the convertion from vcf4 to avinput?(I'am not familar with Perl language.so, it is hard for me to read source code.)

Best regards!
xinchang zheng

**Comment by kaichop** [comment]
It is recommended that you need to do allele splitting first (read
http://annovar.openbioinformatics.org/en/latest/articles/VCF/) and generate
a new VCF file for annotation.
In addition, there is no need to convert to avinput format, you only need
to annotate VCF directly which is the best way for generating an annotation.

The end positions are the same below which is to be expected, since you are
looking at the same CTTTT but with varying start site.

**Comment by zhengxinchang** [comment]
I get the correct results by splitting multiallelics record to multiple records following the instruction you mentioned above. 
thank you very much!
