### ISSUE TITLE
Intermittent lines in output VCF have missing CHROM field

### ISSUE THREAD

**Issue by OgnjenMilicevic** [WGLab/doc-ANNOVAR#71]
Hello!
We used the following databases for annotation of Haplotype Caller outputs:

```
./annotate_variation.pl -buildver hg38 -downdb cytoBand /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar refGene /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar knownGene /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar abraom /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar avsnp150 /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar clinvar_20180603 /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar cosmic70 /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar dbnsfp35a /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar dbscsnv11 /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar ensGene /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar exac03 /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gme /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad_genome /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad211_genome /data/annovar
./annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad211_exome /data/annovar
```

Some entries in the output VCF are missing the chromosome (first tab delimited field in the VCF). What I noticed is that those exact fields have one column less in the corresponding txt produced by ANNOVAR. I cannot see anything unusual in those lines. Can you help me debug this?

Thanks!

**Comment by kaichop** [comment]
This is a known problem. The reason is that some mutation generated by Haplotype Caller has no meaning based on VCF format specification (there is no alternative allele, and the GT field is listed as 0/0).

I had previously updated convert2nnovar.pl to handle this particular situation (essentially treating the ALT as "0", so at least gene-based and region-based annotation can work) but never updated the package itself. I will include this in the latest package to be released soon.
